version: '3'
  
services:
    dmcheck_client_b1_1:
        build: .
        image: neo4j-twittertools
        command: bash -c "python user_friendship.py"
        logging:
         driver: "json-file"
         options:
          max-size: "2m"
          max-file: "2"
        volumes:
            - .env_dmcheck_client_b1_1:/features/config/.env
    dmcheck_client_b1_2:
        build: .
        image: neo4j-twittertools
        command: bash -c "python user_friendship.py"
        logging:
         driver: "json-file"
         options:
          max-size: "2m"
          max-file: "2"
        volumes:
            - .env_dmcheck_client_b1_2:/features/config/.env
    dmcheck_bucket_monitor:
        build: .
        image: neo4j-twittertools
        command: bash -c "python dmcheck_bucket_monitor.py"
        logging:
         driver: "json-file"
         options:
          max-size: "2m"
          max-file: "2"
        volumes:
            - .env_dmbucket_monitor:/features/config/.env
