version: '3'
  
services:
    tweetfetcher:
        build: .
        image: neo4j-twittertools
        command: bash -c "python tweets_fetcher.py"
        logging:
         driver: "json-file"
         options:
          max-size: "2m"
          max-file: "2"
        volumes:
            - .env:/features/config/.env
    dmcheck:
        build: .
        image: neo4j-twittertools
        command: bash -c "python user_friendship.py"
        logging:
         driver: "json-file"
         options:
          max-size: "2m"
          max-file: "2"
        volumes:
            - .env_dmcheck:/features/config/.env

